version: '3.8'
services:
  gateway:
    build: gateway
    #  image: gateway-image
    #  container_name: gateway-container
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    #  image: server-image
    #  container_name: server-container
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - DB_NAME=share
      - DB_HOST=db
      - DB_PORT=5432
      - SERVER_PORT=9090
      - SPRING_DATASOURCE_USERNAME=share
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/share

  db:
    image: postgres
    #  container_name:

    ports:
      #Левая часть — внешний порт
      #правая — порт, на который будет перенаправлен запрос внутри приложения.
      - "6541:5432"

    # volume и связанная с ним директория в контейнере
    volumes:
      - /var/lib/postgresql/data/
    # переменные окружения
    environment:
      - POSTGRES_DB=share
      - POSTGRES_USER=share
      - POSTGRES_PASSWORD=root

